### ISSUE TITLE
几处错误/建议

### ISSUE THREAD

**Issue by chairuosen** [isno/theByteBook#1]
https://isno.github.io/chapter1/latency.html
从 SSD 顺序读取 1 MB         49,000 ns ≈ 4.9 μs   换算错误，应该是49μs

另外 https://isno.github.io/chapter1/bgp.html 最后一段 `在使用多线机房`重复了两次 ，
另外同篇文中首次出现VIP时，建议加注释(Virtual IP ?)，毕竟VIP的常见释义是高级会员

老哥写的很棒，很涨姿势！

**Comment by isno** [comment]
感谢您对错误的甄别，目前所有的文章还为经过校正，我将逐篇修正文稿

**Comment by 0utsiderZhong** [comment]
![image](https://github.com/isno/theByteBook/assets/55649441/d9906195-e8b5-4cb2-85c9-e9c75640db6d)

+1
