### ISSUE TITLE
勘误？

### ISSUE THREAD

**Issue by 31415926535x** [isno/theByteBook#10]
> # 云原生架构的定义
> 另一方面，云原生架构可以**用过与**基础设施的深度整合和优化，将存储、计算、网络等资源管理以及相应的自动化能力交由基础设置执行，应用自身变的更为灵活，从而大幅降低管理成本。

这里的 *云原生架构可以**用过与**基础设施的深度整合和优化*  是不是少了个词呢？

#3

**Comment by isno** [comment]
谢谢提醒，是写错了，预计9月份整体排查一遍。 现在主要的精力还集中在整体内容撰写上
