### ISSUE TITLE
图例标号错误

### ISSUE THREAD

**Issue by hexody** [isno/theByteBook#105]
下文中，如图2-2 应为2-3

2.3.1 域名解析的工作原理
域名解析靠的是 DNS，我们在浏览器输入一个域名时，DNS 负责将该域名解析为相应的 IP 地址，以便后续与目标服务器建立 TCP/IP 连接。探寻 DNS 工作原理之前，我们先了解域名的结构。如图2-2所示，域名是一种树状结构，最顶层的域名是根域名（注意是一个点“.”，它是 .root的含义），然后是顶级域名（top-level domain，简写 TLD），再是一级域名、二级域名、三级域名。

**Comment by isno** [comment]
fixed
