### ISSUE TITLE
此处com.代表什么？

### ISSUE THREAD

**Issue by hexody** [isno/theByteBook#106]
com后为啥有个. 
原文：获取 com.域的 TLD 域名服务器后， 向该地址请求 example.com. 的 权威解析服务器（Authoritative nameserver）。

**Comment by isno** [comment]
一个完整的域名最后面是带个“.”的，意为 “ .root” 根。但实际使用上 “.” 是可以忽略的。你加“." 也能访问。

**Comment by hexody** [comment]
> 一个完整的域名最后面是带个“.”的，意为 “ .root” 根。但实际使用上 “.” 是可以忽略的。你加“." 也能访问。

<img width="1113" alt="image" src="https://github.com/isno/theByteBook/assets/23519359/d209d1fd-e434-41b5-817e-c3d1379fcfea">
试了下浏览器貌似访问不了。但是nslookup和dig都可以

**Comment by Yakima-Teng** [comment]
> > 一个完整的域名最后面是带个“.”的，意为 “ .root” 根。但实际使用上 “.” 是可以忽略的。你加“." 也能访问。
> 
> <img alt="image" width="1113" src="https://private-user-images.githubusercontent.com/23519359/283348927-d209d1fd-e434-41b5-817e-c3d1379fcfea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NTQyNzIsIm5iZiI6MTcxNjU1Mzk3MiwicGF0aCI6Ii8yMzUxOTM1OS8yODMzNDg5MjctZDIwOWQxZmQtZTQzNC00MWI1LTgxN2UtYzNkMTM3OWZjZmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDEyMzI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlODk4ZTg5MGZlYjY1NjAzNWM4ZGY3M2ZjZWNjY2M3MTc1ZDk4ZmYwYTVmZjRkNTkxMTBjNzI1OGNkZGMwYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hbd4MsKKK1tnurtBu2y3FCmdbaI4A_hysvTz8I5eLRA"> 试了下浏览器貌似访问不了。但是nslookup和dig都可以

你用的是https，你看下面的错误信息里提示是ERR_SSL_PROTOCOL_ERROR，其实是可以访问的，但是因为证书配的不是这个域名（末尾带.的域名），所以访问不了。你把https改成http就会发现可以访问。是有响应头和状态码这些服务端返回的信息的。

![image](https://github.com/isno/theByteBook/assets/14058004/85d0c81f-3390-455b-b363-f51022c0111e)
