### ISSUE TITLE
“两个端点之间往往并不是路由路径最短，还是费用最低的策略”这句话没读懂

### ISSUE THREAD

**Issue by hexody** [isno/theByteBook#107]
在2.7节开头

**Comment by isno** [comment]
改成这样：“互联网中两个节点之间往往并不是路径最短，而是各个 AS 连接费用最低的策略”。这样是否能理解？

**Comment by hexody** [comment]
> 改成这样：“互联网中两个节点之间往往并不是路径最短，而是各个 AS 连接费用最低的策略”。这样是否能理解？

可以的。我想指出的是你把“而是”打成了“还是”。这里的AS是可用区的概念吗，前文没有这个缩写释义，我理解为云厂商惯用的AZ概念（Available Zone）

**Comment by isno** [comment]
AS 是  Autonomous System，网络自治域。不是 AZ。

**Comment by hexody** [comment]
感谢回复

**Comment by hexody** [comment]
很实用的书，内容相当不错，出版一定买一本支持 @isno
