### ISSUE TITLE
希望统一英文缩写的格式

### ISSUE THREAD

**Issue by hexody** [isno/theByteBook#110]
有的只有缩写没有全称
有的有全称没有中文释义
有的二者都有
有的是缩写（全称）
有的是全称（缩写）
有的用的是中文扩号，有的是英文括号。。
有的缩写用的大写，全称首字母用小写
有的全小写

希望能全局统一一下（作者别打我）

**Comment by hexody** [comment]
个人建议统一为：缩写(全称，中文释义)，例如：XDP（eXpress Data Path，快速数据路径）（但是你这里用的是全角扩号，建议使用英文半角扩号）

**Comment by isno** [comment]
整体完稿再统一修改。如果你有空可以帮我提 PR 啊  :D
