### ISSUE TITLE
k8s ingress

### ISSUE THREAD

**Issue by DuanNengxin** [isno/theByteBook#138]
<img width="1158" alt="image" src="https://github.com/isno/theByteBook/assets/42426923/9c433e3f-e5d6-474e-9399-96f386f88395">
看文当中写NGINX Ingress Controller 是k8s官方，其实这个是nginx官方维护的（nginx在前）https://docs.nginx.com/nginx-ingress-controller/

这个ingress nginx 是k8s官方维护的（ingress在前），https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/

**Comment by isno** [comment]
ingress 的内容会去掉，容器这一章的内容还在写

**Comment by isno** [comment]
ingress 的内容已经去掉了
