### ISSUE TITLE
笔误：Mebibyte 和 Megabyte 的区分

### ISSUE THREAD

**Issue by mikck** [isno/theByteBook#147]
`注意 Mebibyte 和 Megabyte 的区分，123 Mi = 123*1204*1204B = 129 M，123 M 等于 1*1000*1000字节，所以 1M < 1Mi，显然使用带这个小 i 的更准确。`

https://www.thebyte.com.cn/container/resource-limit.html#%E8%B5%84%E6%BA%90%E8%B0%83%E5%BA%A6

Mi 应该是123 Mi = 123 * 1024 * 1024B = 129 M吧

**Comment by isno** [comment]
我看了好久才发现原来是 1024 写成了 1204，谢谢提醒。
