### ISSUE TITLE
第十一章 FInOps

### ISSUE THREAD

**Issue by ShawnSiao** [isno/theByteBook#162]
是否可以更详细些？FinOps 不仅可以 for k8s，也可以 for 普通资源。
是否可以介绍共享资源池相关概念？
流量在峰谷时资源在按量付费或者包年包月订阅方式，哪种更节省费用，如何做到平滑切换，以及弹性括缩容等？

**Comment by isno** [comment]
FinOps 这一章删掉了，实在没精力写了。我目前的主要精力是把当前总共 10 章内容整理好，后面如果有机会再写 finops 和 serverless

共享资源池、弹性扩缩容在容器概论一章简单介绍过。

**Comment by ShawnSiao** [comment]
您好，邮件已收到。
