### ISSUE TITLE
使用 Service Mesh 的目的

### ISSUE THREAD

**Issue by chesha1** [isno/theByteBook#164]
在[1.6 以解决问题为目的推进架构演进](https://www.thebyte.com.cn/architecture/arc.html)中提到：

> 为了解决微服务框架的 “侵入性问题”，使用 Service Mesh

Service Mesh 最初提出是因为这个吗？感觉主要是为了微服务之间的通信的相关问题吧

**Comment by isno** [comment]
你说的没错，就是解决微服务通信的问题。
 
ServiceMesh 的内容有单独的一章 “ 第八章：后微服务时代”。我还没写完，如果你有耐心，可以等到月底再看。

这一节 [8.2 服务间通信的演化 ](https://www.thebyte.com.cn/ServiceMesh/MicroService-history.html) 讲到了 ServiceMesh 为什么出现，解决什么问题。
