### ISSUE TITLE
笔误

### ISSUE THREAD

**Issue by shuaaaaaaaaaaaa** [isno/theByteBook#166]
**如图:**
![Screenshot_2024-02-23-00-48-24-54_a87fd7db6caa850b517aa6fa9d2fcd0e](https://github.com/isno/theByteBook/assets/63639676/b950958d-321b-4786-b2d8-3680dfb4c3a2)

建议改为_“一波”_或_“一拨”_
参考:
https://m.sohu.com/a/726152669_121124334/?pvid=000115_3w_a

**Comment by shuaaaaaaaaaaaa** [comment]
位于倒数第二行倒数第五个字

**Comment by shuaaaaaaaaaaaa** [comment]
1

**Comment by shuaaaaaaaaaaaa** [comment]
位于倒数第二行倒数第五个字

**Comment by isno** [comment]
好的，谢谢指正！

**Comment by shuaaaaaaaaaaaa** [comment]
![IMG_20240225_051953](https://github.com/isno/theByteBook/assets/63639676/a6dac760-5ba4-4cbb-8931-5384161a8ae7)
