### ISSUE TITLE
第六章从消息到事件流-集群性能压测

### ISSUE THREAD

**Issue by 0utsiderZhong** [isno/theByteBook#20]
![image](https://github.com/isno/theByteBook/assets/55649441/0c014451-30a4-414d-b92d-060c7ce9e33f)
这个是想描述什么方面的内容？

**Comment by isno** [comment]
还没考虑好怎么写，用来给 rocketMQ 压测的

**Comment by isno** [comment]
消息中间件的内容我删除掉了，没有精力再写这部分内容了。
