### ISSUE TITLE
第一章：云技术概论 语病

### ISSUE THREAD

**Issue by songmuhan** [isno/theByteBook#26]
这一段话中：
其次，企业逐渐重视上云，云计算服务商也把建设关注点从基础设施的建设向应用的云架构转变。这个阶段，我们谈充分利用云的特性，解放生产力，助力企业商业价值增长，**对于技术人员而言，就是理解云技术、拥抱云原生的最强的驱动力**。

最后一句话中存在语病，根据我的理解，作者想表达的意思应该是 “企业的重视”是“技术人员的驱动力”，或者”这个转变过程“是”驱动力“。

而最后一句话中的主语是”这个阶段“。

**Comment by songmuhan** [comment]
我更倾向于这种写法：

> 其次，企业逐渐重视上云，云计算服务商也把建设关注点从基础设施的建设向应用型的云架构转变。在这个阶段，我们谈充分利用云的特性解放生产力，助力企业商业价值增长，**而这种转变**对于技术人员而言，就是理解云技术、拥抱云原生的最强的驱动力。

您的这种写法还是需要“动脑子”去找主语：
> 其次，企业逐渐重视上云，云计算服务商也把建设关注点从基础设施的建设向应用型的云架构转变，在这个阶段，我们谈充分利用云的特性解放生产力，助力企业商业价值增长，对于技术人员而言，就是理解云技术、拥抱云原生的最强的驱动力。

**Comment by isno** [comment]
按你的来修改！
