### ISSUE TITLE
疑似笔误

### ISSUE THREAD

**Issue by shusencai** [isno/theByteBook#3]
文章标题：网络虚拟化的基础：network namespace
章节：配置 network namespace
下面的命令创建一对虚拟以太网卡，然后把 veth pair的一端放入 netns1 中, 另外一端放入 netns1中。
我理解第二个 netns1 应该改为 netns2。

**Comment by isno** [comment]
感谢您的建议，是笔误。 另一端要放入 netns2。 已修改！
