### ISSUE TITLE
1.4.1标题错别字

### ISSUE THREAD

**Issue by zhangga** [isno/theByteBook#30]
https://github.com/isno/theByteBook/blob/main/architecture/arc-guide.md#141-%E8%87%AA%E5%AE%9A%E5%90%91%E4%B8%8B%E7%9A%84%E6%8E%A8%E8%BF%9B
![image](https://github.com/isno/theByteBook/assets/12657162/9b070dc7-a3b1-4306-b395-a479f9a4e01f)
【自顶向下】或【自上向下】

**Comment by isno** [comment]
已fix
