### ISSUE TITLE
提一下有个例子写错了

### ISSUE THREAD

**Issue by kamilic** [isno/theByteBook#33]
https://github.com/isno/theByteBook/blob/1d46768dd87d4f66febe07d4fd874de042c80045/content/chapter1/bridge.md?plain=1#L47

应该是 `ip link set veth2-peer up`?

**Comment by isno** [comment]
有两对 veth， veth1 veth1-peer 和 veth2 veth2-peer，第一部分处理的是 veth1 veth1-peer 。下面部分是 veth2。。
