### ISSUE TITLE
1.1.2 基于虚拟机的云计算成熟

### ISSUE THREAD

**Issue by Shuimo03** [isno/theByteBook#35]
原文:
在这期间，出现了云计算领域多个重要里程碑：

IaaS的出现：通过按时计费的方式租借服务器，将资本支出（Capex）转变为运营支出（Opex），这使得云计算得以大规模兴起和普及。
PaaS的出现。
开源IaaS的出现：云计算开始进入开源时代。
开源PaaS的出现。
FaaS的出现。

PaaS和FaaS这里是不是可以简单介绍下？像IaaS的出现一样？

**Comment by isno** [comment]
稍微补充了一点。
