### ISSUE TITLE
1.1.1 图1-2 配图不正确

### ISSUE THREAD

**Issue by leonlyu1996** [isno/theByteBook#40]

**Comment by isno** [comment]
是哪里有错误呢？我没注意到

**Comment by leonlyu1996** [comment]
<img width="777" alt="image" src="https://github.com/isno/theByteBook/assets/10532548/3ee5d2b8-024d-494f-b6c9-665d6cf6e894">
这部分内容和时间、企业对不上

**Comment by isno** [comment]
是写错了，我重新修正
