### ISSUE TITLE
配图笔误:超市->超时

### ISSUE THREAD

**Issue by flyerooo** [isno/theByteBook#43]
https://www.thebyte.com.cn/distributed-system/raft.html#leader-%E9%80%89%E4%B8%BE
![image](https://github.com/isno/theByteBook/assets/6385820/595c27f2-f5f1-473c-8e61-6f2dae71ee55)

**Comment by isno** [comment]
分布式的内容正在重新编写

**Comment by isno** [comment]
已修复
