### ISSUE TITLE
1.5.6勘误

### ISSUE THREAD

**Issue by Shnnli** [isno/theByteBook#45]
如同瀑布流水一般，因为被称为瀑布模型->如同瀑布流水一般，因而被称为瀑布模型

[具体位置链接](https://www.thebyte.com.cn/architecture/devops.html#_1-%E7%80%91%E5%B8%83%E5%BC%80%E5%8F%91:~:text=%E7%80%91%E5%B8%83%E6%B5%81%E6%B0%B4%E4%B8%80%E8%88%AC%EF%BC%8C-,%E5%9B%A0%E4%B8%BA,-%E8%A2%AB%E7%A7%B0%E4%B8%BA%E7%80%91%E5%B8%83)

**Comment by isno** [comment]
谢谢，已fix
