### ISSUE TITLE
笔误CNI flannel

### ISSUE THREAD

**Issue by sunway910** [isno/theByteBook#48]
https://www.thebyte.com.cn/kubernetes/CNI.html

![image](https://github.com/isno/theByteBook/assets/55649441/d82260d8-d8cb-4857-8dd1-242ea970f420)

**Comment by isno** [comment]
k8s 章节写的不行，得重新编写。

**Comment by 0utsiderZhong** [comment]
大佬一个人写一本书，内容很广，写成这样已经很厉害了

- 感觉k8s与容器相关的内容太多了，根本没有办法把所有问题描述清楚。
- 到了书的后几章节，更多的是"原理性"的东西，"实践"相关的内容偏少，毕竟书名叫<深入架构原理与实践>，感觉可以在k8s相关章节写点偏实践的东西，这样看后几章能更加有趣，没那么枯燥。


一点个人建议和想法如下：

- 比如可以写公有云上k8s需要注意什么，需要准备什么，要多少钱
- 云上专有网络 、VPC、VSW、k8s SNAT 是什么怎么用， k8s Pod/Service CIDR 怎么合理配置，公有云提供的网络插件怎么选？
- 云镜像仓库基础版多少钱、k8s日志存储每个月预估多少G要多少钱、k8s暴露服务需要的SLB用什么规格多少钱、ack/eks集群监控规格怎么选多少钱。

**Comment by isno** [comment]
谢谢，目前思路都有了，但落笔写出来还是有挺大难度

**Comment by luommy** [comment]
还没有细读，准备看看不知能不能看懂

**Comment by hexody** [comment]
> 大佬一个人写一本书，内容很广，写成这样已经很厉害了
> 
> * 感觉k8s与容器相关的内容太多了，根本没有办法把所有问题描述清楚。
> * 到了书的后几章节，更多的是"原理性"的东西，"实践"相关的内容偏少，毕竟书名叫<深入架构原理与实践>，感觉可以在k8s相关章节写点偏实践的东西，这样看后几章能更加有趣，没那么枯燥。
> 
> 一点个人建议和想法如下：
> 
> * 比如可以写公有云上k8s需要注意什么，需要准备什么，要多少钱
> * 云上专有网络 、VPC、VSW、k8s SNAT 是什么怎么用， k8s Pod/Service CIDR 怎么合理配置，公有云提供的网络插件怎么选？
> * 云镜像仓库基础版多少钱、k8s日志存储每个月预估多少G要多少钱、k8s暴露服务需要的SLB用什么规格多少钱、ack/eks集群监控规格怎么选多少钱。

加一章FinOps：）

**Comment by isno** [comment]
基本完稿了，差不多就这样了，不增加新内容了。现在要花精力校验之前的内容
