### ISSUE TITLE
在线阅读两篇不同的文章指向的内容一样

### ISSUE THREAD

**Issue by Snailclimb** [isno/theByteBook#49]
感谢作者的原创开源书籍，阅读到容器编排系统 Kubernetes章节的时候发现弹性伸缩和Kubernetes进阶的内容一直，两者使用的同一个链接。

<img width="1146" alt="image" src="https://github.com/isno/theByteBook/assets/29880145/5d405beb-5455-4dc1-b47d-f667d6a74a37">

**Comment by isno** [comment]
容器编排的内容会重新编写，第三章后面的错误，暂时先不修改
