### ISSUE TITLE
笔误

### ISSUE THREAD

**Issue by HCHCO** [isno/theByteBook#53]
用户态返回TCP Option 中的cip。
![image](https://github.com/isno/theByteBook/assets/38172927/31e63ddc-8b54-4851-a31e-05f60fa6724c)

**Comment by HCHCO** [comment]
第四章节 4.1 LVS工作模式。

**Comment by isno** [comment]
谢谢本章正在重写，预计本周内完稿。

**Comment by isno** [comment]
LVS 的细节已经删除，负载均衡主题修改四层、7层概论
