### ISSUE TITLE
[讨论]关于FinOps

### ISSUE THREAD

**Issue by SakaZhang** [isno/theByteBook#6]
这块之前我也比较感兴趣。在前期搜集信息的时候已经看到国内杭州(也许是宁波?)已经有创业公司在做相关的事情，也有中大厂在做这些事(https://www.bilibili.com/read/cv22150189/)，但主要有两个疑惑：
1. 由于某些"安全"上的要求，已经有很多企业在执行"服务下云"了，对于FinOps在国内的应用及前景是不是不太明朗？
2. FinOps比较依赖云厂商给提供的能力，如果某天云厂商觉得被薅疼了，会不会直接关闭或者修改账单功能，这对于FinOps而言是不是也是一种致命威胁？

**Comment by isno** [comment]
我对 finops 的理解还在 ops 上，关注的是如何在技术角度降本。
公有云、私有云都是云，只要业务“在线”，都是在云上啊， 云成本，不论服务下不下云，都在那里！

对于第二条，公有云格局没那么小的

**Comment by SakaZhang** [comment]
嗯，学习了。期待FinOps内容。
