### ISSUE TITLE
感觉为了内容一致性，术语缩写释义 一节中 混沌工程一栏 使用CE 更好？

### ISSUE THREAD

**Issue by wrenashe** [isno/theByteBook#60]
https://github.com/isno/theByteBook/blob/88b872677b258de696a846e6cf5248cc6b9818d5/noun.md?plain=1#L33

 -->
| **CE** | Chaos Engineering | **混沌工程：** 用于故障演练及解决。研究大规模分布式系统瓶颈、缺陷，提升整体服务稳定的方法学|

**Comment by isno** [comment]
混沌工程，很少见用 CE 缩写的。

**Comment by isno** [comment]
😄，受教！
