### ISSUE TITLE
建议HTTPS 原理及 SSL 层优化实践章节新增HTTP 1.1 / HTTP 2.0小章节

### ISSUE THREAD

**Issue by MoshiCoCo** [isno/theByteBook#66]
既然提到了quic，建议同步增加HTTP 1.1 / HTTP 2.0的章节。

目前在各类企业实际生产环境中，1.1/2.0都有在使用，2.0相比于1.1也有比较好的性能提升，对于1.1升级到quic或许是比较激进的，但是1.1到2.0基本可以无感过渡。建议增加这部份的小章节。

**Comment by MoshiCoCo** [comment]
我觉得 HTTP1.1 -> HTTP2.0 ->HTTP3 (QUIC) 去递进介绍或许会好一些，QUIC在目前的实际实践中其实用的还是比较少的，大量业务都是用的1.1/2.0，如果能够补充这里的章节，整体上这一章会比较连贯。（一些拙见，仅仅是一些建议，非常感谢作者写的这本书）

**Comment by isno** [comment]
第二章属于完稿状态，除非有错误，其他不改了。不然整部写不完。

**Comment by isno** [comment]
第二章属于完稿状态，除非有错误，其他不改了。不然整部写不完。
