### ISSUE TITLE
在网络可观测性部分能否增加一些最新的测试工具

### ISSUE THREAD

**Issue by pengjianzhang** [isno/theByteBook#7]
1. dperf https://github.com/baidu/dperf 测试 4 层网络性能，性能最高，dpvs项目在用此工具，国内大厂都在用
2. t-rex https://github.com/cisco-system-traffic-generator/trex-core 测试 3 层、4 层、7 层
3. pktgen https://github.com/pktgen/Pktgen-DPDK 测试 3 层

**Comment by isno** [comment]
已经在了解 dperf 了，我预计主体内容完成时，再完善网络观测篇内容。
