### ISSUE TITLE
存在笔误

### ISSUE THREAD

**Issue by MoneyMissile** [isno/theByteBook#9]
![image](https://github.com/isno/theByteBook/assets/45279094/3b7c5584-9f55-4bb7-b631-d6f659d697c4)
在 分布式理论及实践/幂等性设计 这一章节中，此处标红的“实践”是否为“时间”？

**Comment by MoneyMissile** [comment]
![image](https://github.com/isno/theByteBook/assets/45279094/b95eccdb-5063-4fb9-9cde-9e5cab45407e)

在 分布式理论及实践/分布式事务解决理论：2PC 这一节中，描述有误

**Comment by isno** [comment]
谢谢审阅，已经修复。
