### ISSUE TITLE
5.3.3 Basic Paxos 

### ISSUE THREAD

**Issue by songzhibin97** [isno/theByteBook#96]
> 安全性 Safety：
一个变量只会被确定一个值（只能一个人当村长），一个变量只有在值被确定之后，才能被学习。
活性 Liveness：
提案最终会被接受（一定能选出个村长）；一个提案被接受之后，最终会被学习到。

学习是什么意思。。。

**Comment by isno** [comment]
没写完整。
一个提案被接受之后，最终会被所有的村民（learner）学习到。

第五章我还没写完，所有有不少错误。
